# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - run: echo "text to output here" >  /home/circleci/output.txt
      - persist_to_workspace:
          root:  /home/circleci
          path: output.txt


  print_output_file:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - run: cat  /home/circleci/output.txt
      - attach_workspace:
          at:  /home/circleci


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output

