# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run: aws cloudformation deploy --template-file template.yml --stack-name udacity


workflows:
  # Name the workflow "welcome"
  infra:
    # Run the welcome/run job in its own container
    jobs:
      - create_infra
